# ================================================
# PROFILE: dev — MySQL (mecanica_IFSP)
# ================================================
# Para ativar: altere application.properties para
#   spring.profiles.active=dev

# DATASOURCE
spring.datasource.url=jdbc:mysql://localhost:3306/mecanica_IFSP?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Mmd76448401#

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false